### ISSUE TITLE
NoSuchMethodError，what happening？？？

### ISSUE THREAD

**Issue by SongJayJay** [criccomini/ezdb#11]
public class Test {
	public static void main(String args[]) {
		System.out.println("test!!!!");
		Db ezdb = new EzLevelDb(new File("./data"));
		Table<Integer,Integer> dataTable = ezdb.getTable("test", IntegerSerde.get,  IntegerSerde.get);
		dataTable.put(1, 2);
	}

}

![image](https://user-images.githubusercontent.com/7687021/45986650-6fa1ae00-c09f-11e8-967f-9f46db72eb3a.png)

**Comment by subes** [comment]
https://github.com/google/guava/issues/1846

I am going to upgrade the leveldb dependencies to fix this issue.

**Comment by subes** [comment]
Maven repository:
http://invesdwin.de/artifactory/invesdwin-oss-remote

<dependency>
	<groupId>com.github.criccomini</groupId>
	<artifactId>ezdb-leveldb</artifactId>
	<version>0.1.12</version>
</dependency>

Please try the new release. The guava incompatibility should be fixed by the newer leveldb dependencies.

**Comment by subes** [comment]
Closing this issue. If something new pops up, please reopen.
